-- AlterTable
-- Add EMERGENCY_CALL_INITIATED action for logging that a user opened a tel: link
-- (call initiation only — never completion, dispatch, or acknowledgment).
ALTER TABLE `care_mission_timelines` MODIFY COLUMN `action` ENUM(
  'CARE_MISSION_CREATED',
  'REFERRAL_LINKED',
  'FACILITY_SELECTED',
  'FACILITY_CONTACTED',
  'FACILITY_ACCEPTED',
  'TRANSPORT_ARRANGED',
  'EMERGENCY_CONTACT_NOTIFIED',
  'PATIENT_DEPARTED',
  'PATIENT_ARRIVED',
  'FOLLOW_UP_SCHEDULED',
  'CHECKLIST_ITEM_COMPLETED',
  'CHECKLIST_ITEM_REOPENED',
  'MISSION_ESCALATED',
  'MISSION_COMPLETED',
  'MISSION_CANCELLED',
  'REFERRAL_FOLLOW_UP_DUE',
  'REFERRAL_CLOSED',
  'REFERRAL_CANCELLED',
  'EMERGENCY_CALL_INITIATED'
) NOT NULL;
